config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :fight_cards do
    resources :fights
  end
  match '/signin', to: 'sessions#new', :via => 'get'
  match '/logout', to: 'sessions#destroy', :via => 'delete'
  match '/signup', to: 'users#new', :via => 'get'

end

app/models/fight.rb
class Fight < ActiveRecord::Base
	# belongs_to :user
	belongs_to :fight_card
end

app/models/fight_card.rb
class FightCard < ActiveRecord::Base
	belongs_to :user
	has_many :fights
  	accepts_nested_attributes_for :fights, 
  	:allow_destroy => true, 
  	:reject_if => proc { |att| att['name'].blank? }
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :fight_cards
	# has_many :fights, through: :fight_cards

	def email=(value)
		value = value.strip.downcase
		write_attribute :email, value
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

private

############ user helpers #####################
def signed_in?
	if !current_user
		flash[:alert] = "Please sign in to view that resource"
		redirect_to new_session_path
	end
end

def sign_in(user)
	session[:user_id] = user.id if user.present?
end

def sign_out
	session[:user_id] = nil
end

def current_user
	@current_user ||= User.find(session[:user_id]) if session[:user_id]
rescue 
	# ActiveRecord::RecordNotFound
	@current_user = nil
	session[:user_id] = nil
end

def current_user?
	current_user.present?
end

def correct_user
	@user = User.find(params[:id])
	if current_user != @user
		flash[:alert] = "That does not belong to you!"
		redirect_to new_session_path :notice => "You need to be signed in to access that page"
    end
end

def admin?
	current_user.admin == true
end


helper_method :current_user
helper_method :current_user?
helper_method :admin?

########## fight helpers #############

# def all_card_fights
# 	@fight = Fight.find(params[:id]) 
# end

# helper_method :all_card_fights

end

app/controllers/fight_cards_controller.rb
class FightCardsController < ApplicationController

	before_filter :admin?, :only => [:new, :create, :edit, :update, :destroy]

	def index
		@fightcards = FightCard.all
	end

	def show
		@fightcard = FightCard.find(params[:id])
	end

	def new
		@fightcard = FightCard.new
	end

	def create
		@fightcard = FightCard.new(fight_card_params)
		if @fightcard.save
			redirect_to @fightcard, :notice => "Your fight card was successfully created!"
		else
			render "new"
		end
	end

	def edit
		@fightcard = FightCard.find(params[:id])
	end

	def update
		@fightcard = FightCard.find(params[:id])
		if @fightcard.update_attributes(fight_card_params)
			redirect_to @fightcard, :notice => "Your fight card was successfully updated!"
		else
			render "edit"
		end
	end

	def destroy
		@fightcard = FightCard.find(params[:id])
		@fightcard.destroy
		redirect_to fight_cards_url :notice => "Your fight card was successfully deleted!"
	end

	private

	def fight_card_params
  		params.require(:fight_card).permit(:title, :start_time, :city, :fights_attributes => [:id, :division, :_destroy])
	end

end

app/controllers/fights_controller.rb
class FightsController < ApplicationController

	before_filter :admin?, :only => [:new, :create, :edit, :update, :destroy]

	def index
		@fight = Fight.all
	end

	def show
		@fight = Fight.find(params[:id])
	end

	# def new
	# 	@fight = Fight.new 
	# end

	def create
		@fight = Fight.new(fight_params)
		if @fight.save
			redirect_to @fight, :notice => "Your fight was successfully created!"
		else
			render "new"
		end
	end

	def edit
		@fight = Fight.find(params[:id])
	end

	def update
		@fight = Fight.find(params[:id])
		if @fight.update_attributes(fight_params)
			redirect_to @fight, :notice => "Your fight was successfully updated!"
		else
			render "edit"
		end
	end

	def destroy
		@fight = Fight.find(params[:id])
		@fight.destroy
		redirect_to @fightcard, :notice => "Your fight was successfully deleted!"
	end

	private

	def fight_params
  		params.require(:fight).permit(:division)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		user = User.find_by_email(params[:email].downcase)
		if user && user.authenticate(params[:password])
			session[:user_id] = user.id
			redirect_to user, :notice => "Logged in!"
		else
			flash.now[:alert] = "Invalid password"
			render "new"
		end
	end

	def destroy
		sign_out
		redirect_to users_url
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_filter :signed_in?, :only => [:edit, :update, :destroy]
    before_filter :correct_user, :only => [:edit, :update, :destroy]
    
    def index
        @users = User.all
    end

    def show
  	    @user = User.find(params[:id])
    end

    def new
  	    @user = User.new
    end

    def create
  	    @user = User.new(user_params)
  	    if @user.save
  		      redirect_to users_url, :notice => "Your account was successfully created!"
  	    else
  		      render 'new'
            flash.now[:alert] = "User was not created"
  	    end
    end

    def edit
    end

    def update
  	    if @user.update_attributes(user_params)
  		      redirect_to user_path(@user), :notice => "Your account was successfully updated!"
  	    else
  		      render 'edit'
            flash.now[:alert] = "Your account was not updated!"
  	    end
    end

    def destroy
    	  @user.destroy
    	  redirect_to users_path, :notice => "Your account was successfully deleted!"
    end

    private

    def user_params
    	  params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fight_cards_helper.rb
module FightCardsHelper
end

app/helpers/fights_helper.rb
module FightsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/fight_cards/_createform.html.erb
<%= form_for @fightcard do |f| %>
	<%= f.text_field :title, id:"title", :placeholder => 'Enter your title' %><br />
	<%= f.text_field :start_time, id:"start_time", :placeholder => 'Enter your start time' %><br />
	<%= f.text_field :city, id:"city", :placeholder => 'Enter your city' %><br />

    <span>Fights</span><br />

    <%= f.fields_for :fights, @fightcard.fights.build do |fight_form| %>
        <%= fight_form.label :division %><br />
        <%= fight_form.text_field :division, id:"division" %><br />
    <% end %>

    <%= f.submit 'save' %>

<% end %>

app/views/fight_cards/_errors.html.erb
<% if @fightcard.errors.any? %>
	<% pluralize(@fightcard.errors.count, "errors") %> prohibited this from being saved
	<ul>
	<% @fightcard.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
	<% end %>
	</ul>
<% end %>

app/views/fight_cards/_form.html.erb
<%= form_for @fightcard do |f| %>
	<%= f.text_field :title, id:"title", :placeholder => 'Enter your title' %><br />

	<%= f.text_field :start_time, id:"start_time", :placeholder => 'Enter your start time' %><br />

	<%= f.text_field :city, id:"city", :placeholder => 'Enter your city' %><br />

	<%= f.submit 'save' %>
<% end %>

app/views/fight_cards/_updateform.html.erb
<%= form_for @fightcard do |f| %>
	<%= f.text_field :title, id:"title", :placeholder => 'Enter your title' %><br />
	<%= f.text_field :start_time, id:"start_time", :placeholder => 'Enter your start time' %><br />
	<%= f.text_field :city, id:"city", :placeholder => 'Enter your city' %><br />

	<span>Fights</span><br />

    <%= f.fields_for :fights, @fightcard.fights do |fight_form| %>
        <span>Fight</span><br />
        <%= fight_form.label :division %>
        <%= fight_form.check_box :_destroy %>
        <%= fight_form.label :_destroy, "Remove Question" %>
        <br />
        <%= fight_form.text_field :division, id:"division" %><br />
    <% end %>

    <%= f.submit 'save' %>

<% end %>

app/views/fight_cards/edit.html.erb
<h1>Fight Card #edit</h1>
<%= render :partial => "errors" %>
<%= render :partial => "updateform" %> 
<br>
<%= link_to "Back", fight_card_path %>

app/views/fight_cards/index.html.erb
<h1>Fight Card Index</h1>
<% @fightcards.each do |fightcard| %>
	<%= link_to fightcard.title, fightcard %>
<% end %>

app/views/fight_cards/new.html.erb
<h1>Fight Card #new</h1>
<%= render :partial => "errors" %>
<%= render :partial => "createform" %>

<%= link_to "Back", @fightcard %>

app/views/fight_cards/show.html.erb
<%= @fightcard.title %>
<%= @fightcard.start_time %>
<%= @fightcard.city %>
<br />
<h3>Fights</h3>

<% @fightcard.fights.each do |fight| %>
	<%= fight.division %><br />
<% end %>

<%= link_to 'Edit', edit_fight_card_path(@fightcard) %>
<%= link_to "Delete Fight Card", @fightcard, :confirm => "Are you sure you want to delete this fight card?", :method => :delete %>

app/views/fights/_form.html.erb
<!-- <h3>Fights</h3>
<% @fightcard.fights.each do |fight| %>
	<%= fight.division %>
	<%= link_to "Delete Fight", @fight, :confirm => "Are you sure you want to delete this fight?", :method => :delete %>
	<br />
<% end %>

<%= form_for @fightcard do |f| %>
  <ul>
    <%= f.fields_for :fights, @fightcard.fights.build do |fight_form| %>
    	<span>Fights</span><br />
        <%= fight_form.label :division %><br />
        <%= fight_form.text_field :division, id:"division" %><br />
        <%= fight_form.submit "save" %>
    <% end %>
  </ul>
<% end %> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mma</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<ul>
		<li><%= link_to "All Users", users_url %></li>
		<li><%= link_to "Fight Cards", fight_cards_path%></li>	
		<% if current_user && current_user.admin? %>
		<li><%= link_to "Create a Fight Card", new_fight_card_path%></li>	
		<% end %>	
		<% if current_user? %>
		Signed in as <%= current_user.email %>
		<li><%= link_to "Log out", session_path("current"), :method => :delete %></li>
		<% else %>
		<li><%= link_to "Log in", new_session_path %></li> 
		<li><%= link_to "Sign up", new_user_path %></li>
		<% end %>
	</ul>

	<% if flash[:notice] %>
		<p><%= flash[:notice] %></p>
	<% end %>
	<% if flash[:alert] %>
		<p><%= flash[:alert] %></p>
	<% end %>

<%= yield %>

</body>
</html>

app/views/users/_errors.html.erb
<% if @user.errors.any? %>
	<% pluralize(@user.errors.count, "errors") %> prohibited this from being saved
	<ul>
	<% @user.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
	<% end %>
	</ul>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
	<%= f.text_field :username, id:"username", :placeholder => 'Enter your username' %><br />

	<%= f.text_field :email, id:"email", :placeholder => 'Enter your email' %><br />

	<%= f.text_field :password, id:"password", :placeholder => 'Enter your password' %><br />

	<%= f.text_field :password_confirmation, id:"password_confirmation", :placeholder => 'Confirm your password' %><br />

	<%= f.submit 'save' %>
<% end %>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<%= render :partial => "errors" %>
<%= render :partial => "form" %> 
<br>
<%= link_to "Back", users_url %>

app/views/users/index.html.erb
<h1> This is the user index page </h1>

<table>
    <tr>
    	<th>username</th>
    </tr>

	<% @users.each do |user| %>
	  	<tr>
		    <td><%= link_to user.username, user %></td>
		</tr>
	<% end %>
</table>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= render :partial => "errors" %>
<%= render :partial => "form" %>

<%= link_to "Back", users_url %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p> Username: <%= @user.username %><br />
Email: <%= @user.email %><br />
Wins: <%= @user.wins %><br />
Losses: <%= @user.losses %><br />
Silver: <%= @user.silver %><br /></p>

<% if current_user == @user %>
	<%= link_to 'Edit', edit_user_path(@user) %>
	<%= link_to "Delete User", @user, :confirm => "Are you sure you want to delete this user?", :method => :delete %>
<% end %>